Project capstone
cilfonegabriel/capstone-1 pull request #1
Opened 2022-11-30 21:54 UTC by cilfonegabriel

The purpose of this project is the presentation of the conference that will be given by Barcelo FC.
We worked with two sections, one called HOME and the other ABOUT, both with two different css, js and html.
The README file was also created, containing all the information about the project, including an explanatory video.
First, we proceeded to work on the mobile version and then the desktop version. For the Desktop version, media queries was used, and also the cards of the presenters of the desktop version were created with js.

2022-12-01 21:03 UTC, Ismailco requested changes
#### Hi @cilfonegabriel, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-01 21:03 UTC, Ismailco commented on README.md
> +Here video: [Gabriel Cilfone](https://www.loom.com/share/894ab4daec184cd685fc27d8d9594ad0)
- [x] The video should contain a highlight about a piece of the code you find interesting or is proud of making, kindly consider showing and talking about some piece of code you proud of

2022-12-01 21:03 UTC, Ismailco commented on index.html
> +        </nav>
- [x] The navigation bar is taking up too much space kindly consider reducing the size of the navigation bar so it looks more like the provided design

![Screenshot_20221201_214924](https://user-images.githubusercontent.com/25227022/205156641-9f3c55c0-5022-43ce-8716-2192a1b1a449.png)

2022-12-01 21:03 UTC, Ismailco commented on index.html
> +    </footer>
- [x] The Footer is taking up too much space kindly consider reducing the size of it so it looks more like the provided design

|Your page|Provided design|
|-|-|
|![Screenshot_20221201_215259](https://user-images.githubusercontent.com/25227022/205157063-41683c96-de85-45bf-987f-4644a79bd60e.png)|![Screenshot_20221201_215519](https://user-images.githubusercontent.com/25227022/205157282-46d9cb5f-da15-4683-a5b3-89c45fffa2f7.png)|

2022-12-01 21:03 UTC, Ismailco commented on about.html
> +        </footer>
- [x] The footer on the about page should have a darker background, kindly consider implementing this so your page looks exactly as the provided design

|Your page|Provided design|
|-|-|
|![Screenshot_20221201_215259](https://user-images.githubusercontent.com/25227022/205157613-e2e15b6a-ba08-40ae-8fe8-40084f644c8d.png)|![Screenshot_20221201_215618](https://user-images.githubusercontent.com/25227022/205157639-d26542b4-f6cc-4219-8b6e-05aa6086ef4f.png)|

2022-12-02 18:35 UTC, levy002 requested changes
## Hello @cilfonegabriel   , :wave:
### I'm Levy, your PR reviewer

Excellent work :sunglasses: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 18:35 UTC, levy002 commented on assets/styles/style.css
> +
- [ ] As requested by the previous reviewer, the footer on the about page should have a darker background, kindly consider implementing this so your page looks exactly as the provided design. Please make sure to use the same color as the one on provided Behance design.

   - ### YOUR DESIGN
      ![image](https://user-images.githubusercontent.com/87197412/205362501-44596d97-2f94-4c1b-85f5-ce751f62c251.png)

   - ### PROVIDED DESIGN
   
      ![image](https://user-images.githubusercontent.com/87197412/205362433-83d6e5a5-21d3-4a16-beb4-e86a494d2575.png)

2022-12-02 18:59 UTC, emmiiorji approved these changes
Hi @cilfonegabriel, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/204921935-8884c611-a2b5-4af5-81d5-aff598294d41.gif)

## Good Highlights

- Linter checks are passing
- Good commit messages
- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 19:00 UTC, merged